---
- name: Create a group in an AD
  hosts: all
  tasks:
    - name: Create a group
      microsoft.ad.group:
        name: AD_Pruebas
        scope: global
        members:
          add:
            - Adminstrator@REDSOFT.GT.SV
  
