---
- name: User in an AD
  hosts: all
  tasks:
    - name: Ensure user user is create
      microsoft.ad.user:
        name: Bob
        identity: bob
        firstname: Bob
        surname: Smith
        password: B0bP4ssw0rd
        domain_username: ADDOMAIN\Administrator
        domain_password: Welcome1!
        state: present
