---
- name: Add an user in a group AD
  hosts: all
  tasks:
    - name: Add user
      microsoft.ad.group:
        name: AD_Pruebas
        scope: global
        members:
          add:
            - REDSOFT\Administrator
            - REDSOFT\juanp
  
