---
- name: Create a group in an AD
  hosts: all
  tasks:
    - name: Ensure user bob is created and use custom credentials to create the user
      microsoft.ad.user:
        name: Bob
        identity: bob
        firstname: Bob
        surname: Smith
        password: B0bP4ssw0rd
        domain_username: REDSOFT\Administrator
        domain_password: Redsoft2024
        domain_server: bob@redsoft.gt.sv
        state: present
