---
- name: Package Management Ansible Playbook
  hosts: serverb
  tasks:
    - name: Dowload file
      ansible.builtin.fetch:
        src: /home/alan/file1.tgz
        dest: /home/pcansible/
        flat: yes
