---
- name: Package Management Ansible Playbook
  hosts: checkpoint
  tasks:
    - name: Dowload file
      ansible.builtin.fetch:
        src: /var/log/CPbackup/backups/*.tgz
        dest: /ciscobackup/Checkpoint
        flat: yes
