---
- name: Disable a user in an AD
  hosts: all
  tasks:
    - name: Verify that the user is present in the AD
      microsoft.ad.user:
        name: Bob
        state: present
        
    - name: Disable an user in the AD
      microsoft.ad.user:
        name: Bob
        enabled: no

