---
- name: User in an AD
  hosts: all
  tasks:
    - name: Ensure user user is create
      microsoft.ad.user:
        name: Bob
        identity: bob
        #enabled: no
        enabled: yes
      
