---
- name: Verificación de systema antes del update 
  hosts: all
  become: yes
  tasks:
  - name: Comprobar espacio en disco
    shell: df -h / | tail -n 1 | awk '{print $5}'
    register: disk_space

  - name: Mostra r espacio en disco
    debug:
      msg: "El uso del disco es: {{ disk_space.stdout }}"

  - name: Fallo si el disco está lleno
    fail:
      msg: "El espacio en disco es insuficiente para proceder con la actualización."
    when: disk_space.stdout | regex_replace('%','') | int > 80

  - name: Sumario de verificación
    debug:
      msg: "Todas las verificaciones previas a la actualización han sido exitosas."