---
- name: Flujo de Aprobación de Documentos
  hosts: all
  become: yes
  tasks:
  - name: Actualización de sistema operativo
    dnf:
      name: "*"
      state: latest
    when: ansible_os_family == "RedHat"
