---
- name: Create a group in an AD
  hosts: all
  tasks:
    - name: Create a group
      microsoft.ad.group:
        name: Pruebas
        scope: global
        state: present
    
    - name: Add members to the group, preserving existing membership
      microsoft.ad.group:
        name: Test Group
        scope: domainlocal
        members:
          add:
            - Domain Admins
            - Domain Users
