---
- name: Install and start Apache HTTPD
  hosts: "{{ host }}"
  tasks:
    - name: Ensure httpd is started
      ansible.builtin.service:
        name: http
        state: started
        enabled: true

