---
- name: Install and start Apache HTTPD
  hosts: "{{ host }}"
  become: true
  tasks:
    - name: Ensure httpd is started
      ansible.builtin.dnf:
        name: "{{ servicio }}"
        state: latest
       

