---
- name: Post update validation
  hosts: all
  become: true
  tasks:
  - name: Check system uptime
    command: uptime
    register: uptime_info

  - debug:
      msg: "System uptime: {{ uptime_info.stdout }}"

  - name: Check for critical errors in /var/log/messages
    shell: grep -i "error" /var/log/messages | tail -n 10
    register: log_errors
    failed_when: log_errors.rc == 0
    ignore_errors: yes

  - name: Final validation
    debug:
      msg: "System {{ inventory_hostname }} validated successfully"
