---
- name: Playbook que imprime dos variables
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Imprimir la primera variable
      debug:
        msg: "El valor de var1 es: {{ var1 }}"

    - name: Imprimir la segunda variable
      debug:
        msg: "El valor de var2 es: {{ var2 }}"
