---
- name: Playbook que imprime dos variables
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Limpiar data
      set_fact:
        clean_data: "{{ var1 | regex_replace('}} *}}$', '}') }}"

    - name: Imprimir variable 1
      ansible.builtin.debug:
        msg: "Variable 1: {{ clean_data }}"

    - name: Convertir cadena JSON a diccionario
      set_fact:
        parsed_data: "{{ clean_data | from_json }}"

#    - name: Convertir cadena JSON a diccionario
#      set_fact:
#        manager: "{{ parsed_data.name }}"
#        email: "{{ parsed_data.email_id }}"

#    - name: Imprimir variable 2
#      ansible.builtin.debug:
#        msg: "Manager: {{ manager }}, Email: {{ email }}"
