---
- name: Playbook que imprime dos variables
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Filtrar data
      set_fact:
        dato_limpio: "{{ var1 | regex_replace('\\\\([\"/])', '\\1') | regex_replace('\\\\n|\\\\t', '') | regex_replace('}\\s*}\\s*}$', '}') }}"

    - name: Convertir cadena JSON a diccionario
      set_fact:
        manager: "{{ dato_limpio.name }}"
        email: "{{ dato_limpio.email_id }}"

