---
- name: Playbook que imprime dos variables
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Convertir cadena JSON a diccionario
      set_fact:
        parsed_data: "{{ var1 | from_json }}"

    - name: Convertir cadena JSON a diccionario
      set_fact:
        manager: "{{ parsed_data.name }}"
        email: "{{ parsed_data.email_id }}"

    - name: Imprimir variable 2
      ansible.builtin.debug:
        msg: "Manager: {{ manager }}, Email: {{ email }}"
