---
- name: ReadJsonfile
  hosts: Windows_AD2
  tasks:
    - name: Display the JSON file content
      shell: cat files/users.json
      register: result

    - name: save the Json data to a Variable as a Fact
      set_fact:
        jsondata: "{{ result.stdout | from_json }}"

    - name: setUserName
      set_fact:
        user_name: "{{ jsondata | json_query(jmesquery) }}"
      vars:
        jmesquery: 'user.user'

    - name: setUserPass
      set_fact:
        user_pass: "{{ jsondata | json_query(jmesquery) }}"
      vars:
        jmesquery: 'user.password'

    - name: Debug User values
      debug: msg=" User => {{ user_name }}, UserPass => {{ user_pass }}"


- name: User Create
  hosts: Windows_AD
  vars:
    user: "{{ user_name }}"
  tasks:
    - name: Ensure user user is create
      microsoft.ad.user:
        name: "{{ user }}"
        identity: "{{ user }}"
        firstname: "{{ user }}"
        surname: "{{ user }}"
        password: "{{ user_pass }}"
        domain_username: REDSOFT\Administrator
        domain_password: Redsoft2024
        state: present




