---
- name: Create a group in an AD
  hosts: all
  tasks:
    - name: Delete a member from a group
      microsoft.ad.group:
        name: AD_Pruebas
        scope: global
        members:
          remove:
            - REDSOFT\juanp
  
