---
- name: Update user pass in an AD
  hosts: all
  vars:
    user: Bob
  tasks:
    - name: Ensure "{{ name }}" user is create
      microsoft.ad.user:
        name: "{{ user }}"
        state: present

    - name: Update pass
      microsoft.ad.user:
        name: "{{ name }}"
        update_password: always
        password: Redsoft2024
        
