---
- name: Update user pass in an AD
  hosts: all
  tasks:
    - name: Ensure "{{ user }}" user is create
      microsoft.ad.user:
        name: "{{ user }}"
        state: present

    - name: Update pass
      microsoft.ad.user:
        name: "{{ user }}"
        update_password: always
        password: Guatemala2024
        
