---
- name: Update user pass in an AD
  hosts: all
  tasks:
    - name: Ensure user user is create
      microsoft.ad.user:
        name: Bob
        domain_username: REDSOFT\Administrator
        domain_password: Redsoft2024
        state: present

    - name: Update pass
      microsoft.ad.user:
        name: Bob
        password: Redsoft2024
        domain_username: REDSOFT\Administrator
        domain_password: Redsoft2024
