---
- name: Install and start Apache HTTPD
  hosts: webansible
  tasks:
    - name: Ensure httpd is started
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true
