---
- name: Verificar estado de un usuario en Active Directory
  hosts: all
  gather_facts: no

  tasks:
    - name: Obtener información del usuario en AD
      microsoft.ad.user:
        name: Bob
        account_locked: no
