---
- name: Verificar estado de un usuario en Active Directory
  hosts: all
  gather_facts: no

  tasks:
    - name: Obtener información del usuario en AD
      microsoft.ad.user:
        name: Bob
        #state: present
      register: user_info

    - name: Mostrar información del estado del usuario
      debug:
        msg: '{{ user_info.account_locked }}'
