---
- name: Obtener el manager de un usuario en Active Directory
  hosts: all
  gather_facts: no
  vars:
    grupo_objetivo: "Vacaciones"
  tasks:
    - name: Obtener manager de {{ ad_user}}
      win_shell: |
        Import-Module ActiveDirectory
        $user = Get-ADUser -Identity "{{ ad_user }}" -Properties Manager
        if ($user.Manager) {
          $manager_dn = $user.Manager
          $manager = (Get-ADUser -Identity $manager_dn).Name
          Write-Output $manager
        } else {
          Write-Output "Sin manager"
        }
      register: manager_info

    - name: Fallo al verificar el manager 
      ansible.builtin.fail:
       msg: "Usted no es el administrador del ususario {{ ad_user }} "
      when: manager_info.stdout_lines[0] != user_name

    - name: Obtener todos los grupos del usuario (incluye grupo primario)
      win_shell: |
        Import-Module ActiveDirectory
        Get-ADPrincipalGroupMembership "{{ ad_user }}" | Select-Object -ExpandProperty Name
      register: user_groups

    - name: Verificar si el usuario pertenece al grupo "Vacaciones"
      set_fact:
        pertenece_a_vacaciones: "{{ grupo_objetivo in user_groups.stdout_lines }}"

    - name: Remover de grupo vacaciones
      microsoft.ad.user:
        name: "{{ ad_user }}"
        groups:
          remove:
            - Vacaciones
        enabled: true
        update_password: always
        password: Recovery2025
      when: pertenece_a_vacaciones

    - name: Cambio de contraseña
      microsoft.ad.user:
        name: "{{ ad_user }}"
        enabled: yes
        account_locked: no
        update_password: always
        password: Recovery_2025
      when: not pertenece_a_vacaciones

      
  
