---
- name: Obtener el manager de un usuario en Active Directory
  hosts: all
  gather_facts: no
  vars:
    grupo_objetivo: "Vacaciones"
  tasks:
    - name: Obtener manager de {{ ad_user}}
      win_shell: |
        Import-Module ActiveDirectory
        $user = Get-ADUser -Identity "{{ ad_user }}" -Properties Manager
        if ($user.Manager) {
          $manager_dn = $user.Manager
          $manager = (Get-ADUser -Identity $manager_dn).Name
          Write-Output $manager
        } else {
          Write-Output "Sin manager"
        }
      register: manager_info

    - name: Fallo al verificar el manager 
      ansible.builtin.fail:
       msg: "Usted no es el administrador del ususario {{ ad_user }} "
      when: manager_info.stdout_lines[0] != user_name

    - name: Obtener todos los grupos del usuario (incluye grupo primario)
      win_shell: |
        Import-Module ActiveDirectory
        Get-ADPrincipalGroupMembership "{{ ad_user }}" | Select-Object -ExpandProperty Name
      register: user_groups

    - name: Mostrar todos los grupos del usuario
      debug:
        var: user_groups.stdout_lines

    - name: Verificar si el usuario pertenece al grupo "Vacaciones"
      set_fact:
        pertenece_a_vacaciones: "{{ grupo_objetivo in user_groups.stdout_lines }}"

    - name: Mensaje si pertenece al grupo Vacaciones
      debug:
        msg: "El usuario {{ ad_user }} pertenece al grupo '{{ grupo_objetivo }}'."
      when: pertenece_a_vacaciones

    - name: Mensaje si NO pertenece al grupo Vacaciones
      debug:
        msg: "El usuario {{ ad_user }} NO pertenece al grupo '{{ grupo_objetivo }}'."
      when: not pertenece_a_vacaciones
  
