---
- name: Obtener el manager de un usuario en Active Directory
  hosts: all
  gather_facts: no
  tasks:
    - name: Obtener información del usuario en Active Directory
      win_shell: |
        Import-Module ActiveDirectory
        $user = Get-ADUser -Identity "{{ ad_user }}" -Properties Manager
        if ($user.Manager) {
          $manager_dn = $user.Manager
          $manager = (Get-ADUser -Identity $manager_dn).Name
          Write-Output $manager
        } else {
          Write-Output "Sin manager"
        }
      register: manager_info

    - name: Mostrar el nombre del manager
      debug:
        #msg: "{{ manager_info.stdout }}"
        msg: "{{ manager_info.stdout_lines }}"
      when: manager_info.stdout_lines[0] == user_manager
      register: manager

    - name: Mostrar si es el mismo manager
      debug:
        msg: "Si es el manager"
      when: "{{ manager }}" == "{{ user_name }}"

    
